# Generated by Django 2.1.4 on 2019-04-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issuers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiker', models.CharField(max_length=10, unique=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuers.Issuer')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.Security'),
        ),
    ]
