# Generated by Django 2.1 on 2019-04-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='name',
            field=models.CharField(default='Company Inc.', max_length=10, unique=True),
        ),
    ]
