# Generated by Django 2.1 on 2019-04-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_security_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('low', models.DecimalField(decimal_places=5, max_digits=20)),
                ('high', models.DecimalField(decimal_places=5, max_digits=20)),
                ('avg', models.DecimalField(decimal_places=5, max_digits=20)),
                ('currency', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=50)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Security')),
            ],
        ),
    ]
