# Generated by Django 2.1 on 2019-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'verbose_name_plural': 'Securities'},
        ),
        migrations.AddField(
            model_name='price',
            name='close',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='price',
            name='open',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
