# Generated by Django 2.1 on 2019-04-30 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20190430_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='anount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='balance',
            name='buy_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='buy_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
