# Generated by Django 2.1 on 2019-04-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20190430_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='name',
            field=models.CharField(default='Company Inc.', max_length=10, null=True),
        ),
    ]
