# Generated by Django 2.1 on 2019-05-02 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_auto_20190430_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2018, 8, 1)),
            preserve_default=False,
        ),
    ]
