# Generated by Django 2.1 on 2019-05-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_portfolio_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='change',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
