# Generated by Django 2.1 on 2019-05-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_price_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='change',
        ),
    ]
