# Generated by Django 2.1 on 2019-05-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_auto_20190504_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='security',
            name='sector',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='portfolios.Sector'),
            preserve_default=False,
        ),
    ]
