# Generated by Django 2.1 on 2019-05-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0014_auto_20190505_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='sector',
        ),
    ]
